JSON_BASE_DIR =  "res/jsons"
JSON_BUILDINGS_FILE = JSON_BASE_DIR + "/buildings.json"
JSON_CHARACTERS_FILE = JSON_BASE_DIR + "/characters.json"
JSON_TOWNHALL_LEVELS_FILE = JSON_BASE_DIR + "/townhall_levels.json"
JSON_OBJECT_IDS_FILE = JSON_BASE_DIR + "/obj_ids.json"
JSON_OBJECT_TRAPS_FILE = JSON_BASE_DIR + "/traps.json"

PATH_IMAGE_BARBARIAN    = "res/troops/barbarian.png"
PATH_IMAGE_ARCHER       = "res/troops/archer.png"
PATH_IMAGE_GIANT        = "res/troops/giant.png"
PATH_IMAGE_GOBLIN       = "res/troops/goblin.png"
PATH_IMAGE_WALL_BREAKER = "res/troops/wall_breaker.png"
PATH_IMAGE_BALLOON      = "res/troops/balloon.png"
PATH_IMAGE_WIZARD       = "res/troops/wizard.png"

PATH_IMAGE_TOWNHALL         = "res/other/images/town_hall"
PATH_IMAGE_CASTLE           = "res/army/images/clan_castle"
PATH_IMAGE_WALL             = "res/defenses/images/wall"
PATH_IMAGE_CAMP             = "res/army/images/army_camp"
PATH_IMAGE_BARRACK          = "res/army/images/barracks"
PATH_IMAGE_LAB              = "res/army/images/laboratory"
PATH_IMAGE_SPELL_FACTORY    = "res/army/images/spell_factory"
PATH_IMAGE_BUILDER_HOME     = "res/other/images/builder's_hut"
PATH_IMAGE_ELIXIR_COLLECTOR = "res/resources/images/elixir_collector"
PATH_IMAGE_GOLD_MINE        = "res/resources/images/gold_mine"
PATH_IMAGE_ELIXIR_STORAGE   = "res/resources/images/elixir_storage"
PATH_IMAGE_GOLD_STORAGE     = "res/resources/images/gold_storage"
PATH_IMAGE_CANNON           = "res/defenses/images/cannon"
PATH_IMAGE_ARCHER_TOWER     = "res/defenses/images/archer_tower"
PATH_IMAGE_MORTAR           = "res/defenses/images/mortar"
PATH_IMAGE_AIR_DEFENSE      = "res/defenses/images/air_defense"
PATH_IMAGE_WIZARD_TOWER     = "res/defenses/images/wizard_tower"

PATH_PNG_STAR_VACANT = "res/images/star_vacant.png"
PATH_PNG_STAR_FILLED = "res/images/star_filled.png"
